### ISSUE TITLE
see if we can integrate onlyoffice DocumentServer

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/aydo#2]
see https://github.com/ONLYOFFICE/DocumentServer

see how we can edit an office file using document server

## deployment

- extend docker vbuilder to build sftpgo 
- make docker compose to run document server and sftpgo

**Comment by alichaddad** [comment]
An update: Trying to make the sftpgo files accessible to the document server. Facing some trouble working around the API provided by sftpgo and its oauth scheme.

**Comment by alichaddad** [comment]
It seems that it is not going to be possible to integrate with document server with SFTPGO without some changes to our fork. This is due to issues arising from the authentication system of SFTPGO. The api provided by the document server doesn't offer a lot in terms of connecting to a authenticated server and thus some changes will need to happen to expose the files hosted by SFTPGO.

I tried doing a small change that allowed accessing the API by passing the token through a query parameter(while this is something that most people wouldn't recommend, it is still used in some cases) but this didn't work unfortunately due to the separation between the webclient interface and the API layer, rendering the use of tokens generated by user login unable to be repurposed for the API interface.
Any thoughts on this? @despiegk

**Comment by despiegk** [comment]
we can change it, shouldn't be that much change, expected that we have to change something

**Comment by alichaddad** [comment]
Integration is almost done, some minor issues to be fixed and finishing the docker configuration

**Comment by alichaddad** [comment]
Integration is done with SFTPGO

**Comment by despiegk** [comment]
wow, how to use & deploy?

**Comment by xmonader** [comment]
should be as simple as editing a doc file from the file manager

**Comment by mohamedamer453** [comment]
Verified.

DocumentServer was added and it works fine, it allows the user to edit files with all of the functionalities needed.

[Screencast from 01-06-23 14:47:26.webm](https://github.com/freeflowuniverse/aydo/assets/101194226/b9845037-caa5-4485-ae7e-d9707be529f1)
